package ru.eddyz.telegrambot.domain.enums;

public enum ButtonsIds {

    //wallet
    INSTALL_NUMBER_WALLET,
    UP_BALANCE,
    WITHDRAW_MONEY,
    CLOSE_WALLET, WITHDRAW_MONEY_HISTORY,

    //withdraw pages
    WITHDRAW_NEXT_BUTTON,
    WITHDRAW_PREV_BUTTON,
    WITHDRAW_CLOSE,

    //payments pages
    PAYMENT_NEXT_BUTTON,
    PAYMENT_PREV_BUTTON,
    PAYMENT_CLOSE,

    //insurance
    INSURANCE_BUY,
    INSURANCE_CLOSE,
    INSURANCE_HISTORY,

    INSURANCE_NEXT_BUTTON,
    INSURANCE_PREV_BUTTON,

    //history list
    HISTORY_NEXT_BUTTON,
    HISTORY_PREV_BUTTON,
    HISTORY_CLOSE,
    HISTORY_REMOVE_BUTTON,
    HISTORY_PUBLISH_BUTTON,
    HISTORY_PRICE_BUTTON,
    HISTORY_ALL_FILES_BUTTON,
    HISTORY_EDIT_BUTTON,

}
